const pets = [
    {
        id: 1,
        name: "Bella",
        age: 2,
        breed: "Golden Retriever",
        category: "Dogs",
        imageUrl: "https://img.freepik.com/photos-gratuite/tir-vertical-chien-mignon-assis-tissu-blanc-moelleux_181624-35794.jpg",
        about: "A playful and friendly dog who loves walks.",
        sex: "female",
        weight: 25,
        user: { name: "Lamiae", email: "lamiae@example.com", imageUrl: "https://randomuser.me/api/portraits/women/1.jpg" }
    },
    {
        id: 2,
        name: "Max",
        age: 4,
        breed: "Yorkshire Terrier",
        category: "Dogs",
        imageUrl: "https://img.freepik.com/psd-premium/yorkshire-terrier-souriant_1225080-167.jpg",
        about: "Loyal and protective, enjoys outdoor activities.",
        sex: "male",
        weight: 30,
        user: { name: "Youssef", email: "youssef@example.com", imageUrl: "https://randomuser.me/api/portraits/men/2.jpg" }
    },
    {
        id: 3,
        name: "Luna",
        age: 1,
        breed: "British Shorthair",
        category: "Cats",
        imageUrl: "https://img.freepik.com/photos-gratuite/kitty-mur-monochrome-derriere-elle_23-2148955134.jpg",
        about: "Calm and affectionate, loves sunbathing.",
        sex: "female",
        weight: 4,
        user: { name: "Sara", email: "sara@example.com", imageUrl: "https://randomuser.me/api/portraits/women/3.jpg" }
    },
    {
        id: 4,
        name: "Oliver",
        age: 3,
        breed: "Domestic Shorthair",
        category: "Cats",
        imageUrl: "https://img.freepik.com/vecteurs-premium/image-du-chat-du-chaton_1138544-24407.jpg",
        about: "Curious and playful, enjoys chasing toys.",
        sex: "male",
        weight: 5,
        user: { name: "Adam", email: "adam@example.com", imageUrl: "https://randomuser.me/api/portraits/men/4.jpg" }
    },
    {
        id: 5,
        name: "Charlie",
        age: 5,
        breed: "Golden Retriever",
        category: "Dogs",
        imageUrl: "https://img.freepik.com/photos-premium/portrait-gros-plan-golden-retriever-assis-exterieur_1048944-24594517.jpg",
        about: "Friendly and energetic, loves swimming.",
        sex: "male",
        weight: 28,
        user: { name: "Mina", email: "mina@example.com", imageUrl: "https://randomuser.me/api/portraits/women/5.jpg" }
    },
    {
        id: 6,
        name: "Milo",
        age: 2,
        breed: "Siamese Mix",
        category: "Cats",
        imageUrl: "https://img.freepik.com/vecteurs-premium/chat-brun-blanc-queue-blanche-est-assis-surface-grise_1138544-49525.jpg",
        about: "Talkative and intelligent, loves exploring.",
        sex: "male",
        weight: 4,
        user: { name: "Rachid", email: "rachid@example.com", imageUrl: "https://randomuser.me/api/portraits/men/6.jpg" }
    },
    {
        id: 7,
        name: "Rocky",
        age: 3,
        breed: "French Bulldog",
        category: "Dogs",
        imageUrl: "https://img.freepik.com/photos-premium/portrait-gros-plan-chien-fond-blanc_1048944-24872664.jpg",
        about: "Strong and calm, enjoys short walks.",
        sex: "male",
        weight: 24,
        user: { name: "Imane", email: "imane@example.com", imageUrl: "https://randomuser.me/api/portraits/women/7.jpg" }
    },
    {
        id: 8,
        name: "Coco",
        age: 1,
        breed: "Hawfinch",
        category: "Birds",
        imageUrl: "https://img.freepik.com/photos-gratuite/gros-plan-hawfinch-male-assis-branche_181624-26251.jpg",
        about: "Colorful and talkative, loves attention.",
        sex: "female",
        user: { name: "Nabil", email: "nabil@example.com", imageUrl: "https://randomuser.me/api/portraits/men/8.jpg" }
    },
    {
        id: 9,
        name: "Kiwi",
        age: 2,
        breed: "Cardinal",
        category: "Birds",
        imageUrl: "https://img.freepik.com/photos-gratuite/capture-selective-cardinal-du-nord-perche-branche_181624-39041.jpg",
        about: "Melodious singer, cheerful in the mornings.",
        sex: "male",
        user: { name: "Salma", email: "salma@example.com", imageUrl: "https://randomuser.me/api/portraits/women/9.jpg" }
    },
    {
        id: 10,
        name: "Nemo",
        age: 1,
        breed: "Goldfish",
        category: "Fish",
        imageUrl: "https://img.freepik.com/photos-gratuite/close-up-belle-poisson-rouge_1137-261.jpg",
        about: "Vibrant and playful, enjoys swimming around.",
        sex: "male",
        user: { name: "Hassan", email: "hassan@example.com", imageUrl: "https://randomuser.me/api/portraits/men/10.jpg" }
    },
    {
        id: 11,
        name: "Dory",
        age: 2,
        breed: "Guppy",
        category: "Fish",
        imageUrl: "https://img.freepik.com/photos-gratuite/gros-plan-million-poissons-au-dessus-sol-sablonneux-dans-aquarium_181624-30818.jpg",
        about: "Curious and friendly, loves hiding in coral.",
        sex: "female",
        user: { name: "Lina", email: "lina@example.com", imageUrl: "https://randomuser.me/api/portraits/women/11.jpg" }
    },
    {
        id: 12,
        name: "Buddy",
        age: 6,
        breed: "Poodle",
        category: "Dogs",
        imageUrl: "https://img.freepik.com/photos-premium/caniche-9-ans-portrait-chien-isole_191971-2321.jpg",
        about: "Happy-go-lucky, loves sniffing around.",
        sex: "male",
        weight: 22,
        user: { name: "Omar", email: "omar@example.com", imageUrl: "https://randomuser.me/api/portraits/men/12.jpg" }
    },
    {
        id: 13,
        name: "Simba",
        age: 2,
        breed: "Domestic Shorthair",
        category: "Cats",
        imageUrl: "https://img.freepik.com/photos-gratuite/portrait-belle-chatte-race-pure-cheveux-courts-collier-orange-cou-assis-sol-reagissant-au-flash-appareil-photo-effraye-regardant-interieur_8353-12551.jpg",
        about: "Majestic and playful, enjoys climbing.",
        sex: "male",
        weight: 6,
        user: { name: "Farah", email: "farah@example.com", imageUrl: "https://randomuser.me/api/portraits/women/13.jpg" }
    },
    {
        id: 14,
        name: "Ruby",
        age: 1,
        breed: "Butterfly Fish",
        category: "Fish",
        imageUrl: "https://img.freepik.com/photos-gratuite/poisson-papillon-bande-cuivree-chelmon-rostratus-poisson-marin-beaux-poissons-fonds-marins-recifs-coralliens_488145-1950.jpg",
        about: "Small and bright, enjoys swimming in circles.",
        sex: "female",
        user: { name: "Khalid", email: "khalid@example.com", imageUrl: "https://randomuser.me/api/portraits/men/14.jpg" }
    },
    {
        id: 15,
        name: "Shadow",
        age: 4,
        breed: "Golden Retriever",
        category: "Dogs",
        imageUrl: "https://img.freepik.com/photos-gratuite/prise-vue-verticale-superficielle-mignon-chiot-golden-retriever-assis-terrain-herbe_181624-27259.jpg",
        about: "Energetic and adventurous, loves running.",
        sex: "male",
        weight: 27,
        user: { name: "Aya", email: "aya@example.com", imageUrl: "https://randomuser.me/api/portraits/women/15.jpg" }
    },
    {
        id: 16,
        name: "Mimi",
        age: 3,
        breed: "Domestic Longhair",
        category: "Cats",
        imageUrl: "https://img.freepik.com/photos-premium/close-up-du-chat-assis-rebord-fenetre_1048944-23896715.jpg",
        about: "Gentle and affectionate, loves cuddling.",
        sex: "female",
        weight: 5,
        user: { name: "Yassine", email: "yassine@example.com", imageUrl: "https://randomuser.me/api/portraits/men/16.jpg" }
    },
    {
        id: 17,
        name: "Sunny",
        age: 2,
        breed: "Sparrow",
        category: "Birds",
        imageUrl: "https://img.freepik.com/photos-premium/gros-plan-oiseau-perche-branche_1048944-1570432.jpg",
        about: "Cheerful and social, enjoys being around people.",
        sex: "female",
        user: { name: "Nada", email: "nada@example.com", imageUrl: "https://randomuser.me/api/portraits/women/17.jpg" }
    },
    {
        id: 18,
        name: "Jack",
        age: 5,
        breed: "Yorkshire Terrier",
        category: "Dogs",
        imageUrl: "https://img.freepik.com/photos-premium/yorkshire-terrier-queue-cheval-manteau-jaune_23-2147840883.jpg",
        about: "Strong and playful, loves training games.",
        sex: "male",
        weight: 29,
        user: { name: "Hanae", email: "hanae@example.com", imageUrl: "https://randomuser.me/api/portraits/women/18.jpg" }
    },
    {
        id: 19,
        name: "Oscar",
        age: 1,
        breed: "Angelfish",
        category: "Fish",
        imageUrl: "https://img.freepik.com/photos-premium/close-up-poisson-ange-face-bleue-nageant-dans-mer_1048944-28275598.jpg",
        about: "Vibrant and solitary, enjoys exploring plants.",
        sex: "male",
        user: { name: "Karim", email: "karim@example.com", imageUrl: "https://randomuser.me/api/portraits/men/19.jpg" }
    },
    {
        id: 20,
        name: "Blue",
        age: 4,
        breed: "Cockatiel",
        category: "Birds",
        imageUrl: "https://img.freepik.com/photos-gratuite/photo-verticale-adorable-cockatiel_181624-42514.jpg",
        about: "Intelligent and colorful, enjoys mimicking sounds.",
        sex: "male",
        user: { name: "Leila", email: "leila@example.com", imageUrl: "https://randomuser.me/api/portraits/women/20.jpg" }
    }
];